input {
  file {
    path => "/var/log/app/webapp.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"         
  }
}

filter {
  grok {
    match => {
      "message" => "%{TIMESTAMP_ISO8601:timestamp} \[%{LOGLEVEL:level}\] Prediction: %{WORD:prediction} for input: %{GREEDYDATA:input}"
    }
  }

  date {
    match => ["timestamp", "yyyy-MM-dd HH:mm:ss"]
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "webapp-logs"
  }

  stdout {
    codec => rubydebug
  }
}
